# Generated by Django 2.2.1 on 2019-06-18 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdresAte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование')),
            ],
            options={
                'verbose_name_plural': 'Адреса АТЕ',
                'verbose_name': 'Адрес АТЕ',
            },
        ),
        migrations.CreateModel(
            name='KlassifPriznakUgroza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование')),
            ],
            options={
                'verbose_name_plural': 'Классифицирующие признаки (угроза)',
                'verbose_name': 'Классифицирующий признак (угроза)',
            },
        ),
        migrations.CreateModel(
            name='KlassifPriznakUK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование')),
            ],
            options={
                'verbose_name_plural': 'Классифицирующие признаки (по статье УК РФ)',
                'verbose_name': 'Классифицирующий признак (по статье УК РФ)',
            },
        ),
        migrations.CreateModel(
            name='ResultProverki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование')),
            ],
            options={
                'verbose_name_plural': 'Результаты проверок',
                'verbose_name': 'Результа проверки',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование')),
            ],
            options={
                'verbose_name_plural': 'Статусы',
                'verbose_name': 'Статус',
            },
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
            ],
            options={
                'verbose_name_plural': 'Подразделения',
                'verbose_name': 'Подразделение',
            },
        ),
        migrations.CreateModel(
            name='Titul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('nomer_vhodyaschego', models.CharField(blank=True, max_length=300, verbose_name='Номер входящего документа')),
                ('date_vhodyaschego', models.DateField(blank=True, verbose_name='Дата входящего документа')),
                ('otkuda', models.CharField(blank=True, max_length=100, verbose_name='Откуда поступил документ')),
                ('ishodyaschii_nomer', models.CharField(blank=True, max_length=50, verbose_name='Исходящий номер документа')),
                ('date_ishodyaschego', models.DateField(blank=True, verbose_name='Дата исходящего документа')),
                ('date_vneseniya', models.DateTimeField(blank=True, verbose_name='Дата вненсения документа в ИБД')),
            ],
            options={
                'verbose_name_plural': 'Титулы',
                'verbose_name': 'Титул',
            },
        ),
        migrations.CreateModel(
            name='TypeMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование')),
            ],
            options={
                'verbose_name_plural': 'Типы сообщений',
                'verbose_name': 'Тип сообщения',
            },
        ),
        migrations.CreateModel(
            name='TypeProverki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование')),
            ],
            options={
                'verbose_name_plural': 'Виды проверок',
                'verbose_name': 'Вид проверки',
            },
        ),
        migrations.CreateModel(
            name='Zvanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование')),
            ],
            options={
                'verbose_name_plural': 'Звания',
                'verbose_name': 'Звание',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('subdivision', models.ForeignKey(default='ГУСБ', on_delete=django.db.models.deletion.PROTECT, to='orion.Subdivision', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name_plural': 'Профили пользователя',
                'verbose_name': 'Профиль пользователя',
            },
        ),
        migrations.CreateModel(
            name='Organizatsiya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование организации')),
                ('inn_ogrn', models.CharField(blank=True, max_length=100, verbose_name='ИНН (ОГРН)')),
                ('adres_organiz', models.CharField(blank=True, max_length=100, verbose_name='Адрес организации')),
                ('inaya_informaciya', models.TextField(blank=True, verbose_name='Иная организация')),
                ('adres_organiz_ate', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='orion.AdresAte', verbose_name='Адрес организации (АТЕ)')),
            ],
            options={
                'verbose_name_plural': 'Организации',
                'verbose_name': 'Организация',
            },
        ),
        migrations.CreateModel(
            name='OperativnayaObstanovka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('klassif_priznak_text', models.TextField(blank=True, verbose_name='Классифицирующий признак (текст)')),
                ('sut_info', models.TextField(verbose_name='Суть информации')),
                ('prinyatie_meri', models.TextField(blank=True, verbose_name='Принятые меры')),
                ('klassif_priznak_ugroza', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='orion.KlassifPriznakUgroza', verbose_name='Классифицирующий признак (угроза)')),
            ],
            options={
                'verbose_name_plural': 'Оперативные обстановки',
                'verbose_name': 'Оперативная обстановка',
            },
        ),
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiya', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('imya', models.CharField(max_length=100, verbose_name='Имя')),
                ('otchestvo', models.CharField(max_length=100, verbose_name='Отчество')),
                ('date_rojdeniya', models.DateField(verbose_name='Дата рождения')),
                ('mesto_rojdeniya_raion', models.CharField(blank=True, max_length=100, verbose_name='Место рождения (район)')),
                ('mesto_rojdeniya_np', models.CharField(blank=True, max_length=100, verbose_name='Место рождения (н.п.)')),
                ('dopolnitelnaya_info', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('mesto_rojdeniya_ATE', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orion.AdresAte', verbose_name='Место рождения (АТЕ))')),
                ('rodstvennie_svyazi', models.ManyToManyField(blank=True, to='orion.Face', verbose_name='Родственные связи')),
                ('zvanie', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='orion.Zvanie', verbose_name='Воинское (специальное) звание')),
            ],
            options={
                'verbose_name_plural': 'Лица',
                'verbose_name': 'Лицо',
                'unique_together': {('familiya', 'imya', 'otchestvo', 'date_rojdeniya', 'mesto_rojdeniya_ATE')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registratsii', models.DateField(verbose_name='Дата регистрации')),
                ('reg_number', models.CharField(max_length=50, verbose_name='Регистрационный номер')),
                ('sut_info', models.TextField(verbose_name='Суть информации')),
                ('klassif_priznak_text', models.TextField(blank=True, verbose_name='Классифицирующий признак (текст)')),
                ('rezolyutsiya_rukovodstva', models.TextField(blank=True, verbose_name='Резолюция руководства ВНГ, ГУСБ')),
                ('srok_ispolneniya', models.DurationField(blank=True, verbose_name='Срок исполнения')),
                ('ispolnitel_organ', models.CharField(blank=True, max_length=100, verbose_name='Исполнитель (Орган)')),
                ('ispolnitel_sotrudnik', models.CharField(blank=True, max_length=100, verbose_name='Исполннитель (сотрудник)')),
                ('info_otrabotki_materiala', models.TextField(blank=True, verbose_name='Информация, полученная в ходе отработки материала')),
                ('prinyatie_meri', models.TextField(blank=True, verbose_name='Принятые меры')),
                ('otvet_zayavitelyu', models.TextField(blank=True, verbose_name='Ответ заявителю')),
                ('ispolnenie_rezolyucii', models.TextField(blank=True, verbose_name='Исполнение резолюции руководства ВНГ, ГУСБ')),
                ('data_otveta', models.DateField(blank=True, verbose_name='Дата ответа заявителю')),
                ('ishodyaschii_nomer', models.CharField(blank=True, max_length=50, verbose_name='Исходящий номер документа')),
                ('date_creation', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('identified_face', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='orion.Face', verbose_name='В ходе проверки выявлены (установленны лица)')),
                ('klassif_priznak_UK', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='orion.KlassifPriznakUK', verbose_name='Классифицирующий признак (по статье УК РФ)')),
                ('klassif_priznak_ugroza', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='orion.KlassifPriznakUgroza', verbose_name='Классифицирующий признак (угроза)')),
                ('operativnaya_obstanovka', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='orion.OperativnayaObstanovka', verbose_name='Оперативная обстановка')),
                ('organizatsiya', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='orion.Organizatsiya', verbose_name='Организация')),
                ('rezult_proverki', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='orion.ResultProverki', verbose_name='Результат проверки')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orion.Status', verbose_name='Пользователь')),
                ('subdivision', models.ForeignKey(default='ГУСБ', on_delete=django.db.models.deletion.PROTECT, to='orion.Subdivision', verbose_name='Подразделение')),
                ('titul', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='orion.Titul', verbose_name='Титул')),
                ('type_message', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='orion.TypeMessage', verbose_name='Тип сообщения')),
                ('type_proverki', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='orion.TypeProverki', verbose_name='Вид проверки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
