# Generated by Django 2.2.1 on 2019-09-17 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='mesto_rojdeniya_ATE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orion.AdresAte', verbose_name='Место рождения (АТЕ))'),
        ),
    ]
