# Generated by Django 2.2.1 on 2019-06-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='srok_ispolneniya',
        ),
        migrations.AddField(
            model_name='event',
            name='date_finish',
            field=models.DateField(null=True, verbose_name='Дата конец'),
        ),
        migrations.AddField(
            model_name='event',
            name='date_start',
            field=models.DateField(null=True, verbose_name='Дата начало'),
        ),
    ]
