# Generated by Django 2.2.1 on 2019-06-20 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orion', '0002_auto_20190619_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orion.TypeMessage', verbose_name='Тип сообщения'),
        ),
    ]
