# Generated by Django 2.2.1 on 2019-06-21 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orion', '0003_auto_20190620_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data_otveta',
            field=models.DateField(blank=True, null=True, verbose_name='Дата ответа заявителю'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orion.Status', verbose_name='Статус'),
        ),
    ]
