# Generated by Django 2.2.1 on 2019-09-18 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orion', '0003_auto_20190917_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='orion.AdresAte', verbose_name='Субъект РФ'),
            preserve_default=False,
        ),
    ]
