# Generated by Django 2.2.1 on 2019-06-21 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orion', '0004_auto_20190621_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='identified_face',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orion.Face', verbose_name='В ходе проверки выявлены (установленны лица)'),
        ),
    ]
