# Generated by Django 2.2.1 on 2019-06-21 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orion', '0005_auto_20190621_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='klassif_priznak_UK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orion.KlassifPriznakUK', verbose_name='Классифицирующий признак (по статье УК РФ)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='klassif_priznak_ugroza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orion.KlassifPriznakUgroza', verbose_name='Классифицирующий признак (угроза)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='operativnaya_obstanovka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orion.OperativnayaObstanovka', verbose_name='Оперативная обстановка'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rezult_proverki',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orion.ResultProverki', verbose_name='Результат проверки'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type_proverki',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orion.TypeProverki', verbose_name='Вид проверки'),
        ),
    ]
