# Generated by Django 2.2.1 on 2019-06-21 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orion', '0006_auto_20190621_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizatsiya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orion.Organizatsiya', verbose_name='Организация'),
        ),
    ]
