# Generated by Django 2.2.1 on 2019-06-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orion', '0008_auto_20190621_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titul',
            name='date_ishodyaschego',
            field=models.DateField(blank=True, null=True, verbose_name='Дата исходящего документа'),
        ),
        migrations.AlterField(
            model_name='titul',
            name='date_vhodyaschego',
            field=models.DateField(blank=True, null=True, verbose_name='Дата входящего документа'),
        ),
        migrations.AlterField(
            model_name='titul',
            name='date_vneseniya',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата вненсения документа в ИБД'),
        ),
    ]
