# Generated by Django 2.2.1 on 2019-06-25 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orion', '0009_auto_20190621_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='zvanie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orion.Zvanie', verbose_name='Воинское (специальное) звание'),
        ),
        migrations.AlterField(
            model_name='operativnayaobstanovka',
            name='klassif_priznak_ugroza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orion.KlassifPriznakUgroza', verbose_name='Классифицирующий признак (угроза)'),
        ),
        migrations.AlterField(
            model_name='organizatsiya',
            name='adres_organiz_ate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orion.AdresAte', verbose_name='Адрес организации (АТЕ)'),
        ),
        migrations.AlterField(
            model_name='organizatsiya',
            name='inaya_informaciya',
            field=models.TextField(blank=True, verbose_name='Иная информация'),
        ),
    ]
